{
  pkgs,
  ...
}:

{
  imports = [
    # Import the machine-specific hardware configuration.
    # This file is generated by `nixos-generate-config` and should not be version-controlled directly.
    # Instead, copy your generated file to this location.
    ./hardware-configuration.nix

    ./confModules/boot.nix
    ./confModules/networking.nix
    ./confModules/desktop.nix
    ./confModules/audio.nix
    ./confModules/users.nix
    ./confModules/packages.nix
    ./confModules/stylix
    ./confModules/mounts.nix
  ];

  stylixModule.enable = true;

  time.timeZone = "Europe/Lisbon";
  system.stateVersion = "25.11";
}
